Vagrant.configure("2") do |config|
  config.vm.provision "shell", inline: <<-SHELL
      apt-get update -y
      echo "10.0.0.10  master-node" >> /etc/hosts
      echo "10.0.0.11  worker-node01" >> /etc/hosts
      echo "10.0.0.12  worker-node02" >> /etc/hosts
  SHELL
  
  config.vm.define "master" do |master|
  config.vm.provision "shell", inline: <<-SHELL
    echo 'master setting up'
    git clone https://github.com/austineisele/kubeadm_scripts.git
    cd ~/kubeadm_scripts/Scripts/ubuntu
    chmod +x all_nodes.sh
    chmod +x master_node.sh
    ./all_nodes.sh
    SHELL
    master.vm.box = "bento/ubuntu-22.04"
    master.vm.hostname = "master-node"
    master.vm.network "private_network", ip: "10.0.0.10"
    master.vm.provider "libvirt" do |vb|
        vb.memory = 4048
        vb.cpus = 2
    end
  end

  (1..2).each do |i|

  config.vm.define "node0#{i}" do |node|
  config.vm.provision "shell", inline: <<-SHELL
    echo 'nodes setting up'
    git clone https://github.com/austineisele/kubeadm_scripts.git
    cd ~/kubeadm_scripts/Scripts/ubuntu
    chmod +x all_nodes.sh
    chmod +x master_node.sh
    ./all_nodes.sh
  SHELL
    node.vm.box = "bento/ubuntu-22.04"
    node.vm.hostname = "worker-node0#{i}"
    node.vm.network "private_network", ip: "10.0.0.1#{i}"
    node.vm.provider "libvirt" do |vb|
        vb.memory = 2048
        vb.cpus = 1
    end
  end
  
  end
end
